---
# tasks file for haproxy
- name: Setup haproxy
  become: yes
  tags:
    - haproxy
  block:
    - name: Install haproxy
      dnf:
        name: haproxy
        state: present
    - name: Enable haproxy on boot
      systemd:
        name: haproxy
        enabled: yes
    - name: Setup haproxy config
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: reload haproxy
    - name: Open firewall port
      firewalld:
        service: http
        permanent: yes
        immediate: yes
        state: enabled
    - name: Start haproxy
      systemd:
        name: haproxy
        state: started
...
